# Basic
title: Mongtoview
author: Seeyong LEe
description: Dreaming Interview Magazine

url: "https://mongtoview.github.io"

permalink: /:year/:month/:title/

# Format
highlighter: rouge
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", tables]

# Pagination
gems: [jekyll-paginate]
paginate: 15
paginate_path: "pages/:num/"

# Social
social:
    weibo: 
    github: mongtoview
    gplus: 112547382138552250597
    mail: mic8816@gmail.com
